// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATmlfx0sMVGypqilWVOycr00EfO6gesbQ',
    appId: '1:854697612175:web:ee6bf06b0dea28485f31fa',
    messagingSenderId: '854697612175',
    projectId: 'bukuapps',
    authDomain: 'bukuapps.firebaseapp.com',
    storageBucket: 'bukuapps.appspot.com',
    measurementId: 'G-P28CT5K32E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5nriR1dRYAtL0_TqV1NPtQNvC1DUZLuc',
    appId: '1:854697612175:android:4ae239f1fb162f525f31fa',
    messagingSenderId: '854697612175',
    projectId: 'bukuapps',
    storageBucket: 'bukuapps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtkzPcfQJwKrlX_kL_F4kJ05BA5e96-yw',
    appId: '1:854697612175:ios:6ade2ed917a845635f31fa',
    messagingSenderId: '854697612175',
    projectId: 'bukuapps',
    storageBucket: 'bukuapps.appspot.com',
    iosBundleId: 'com.bukuresep.bukuResep',
  );
}
